package com.example.ui.util

import androidx.compose.ui.unit.LayoutDirection

object AppStrings {

    fun get(key: String, lang: String = "en"): String {
        val dict = when (lang) {
            "ar" -> ARABIC
            "fr" -> FRENCH
            else -> ENGLISH
        }
        return dict[key] ?: ENGLISH[key] ?: key
    }

    fun getLayoutDirection(lang: String): LayoutDirection {
        return if (lang == "ar") LayoutDirection.Rtl else LayoutDirection.Ltr
    }

    private val ENGLISH = mapOf(
        "app_name" to "StudyMate AI",
        "tagline" to "Your AI Study Partner",
        "hero_title" to "Study smarter. Understand faster.",
        "hero_subtitle" to "Your personal AI-powered academic assistant for solving problems, understanding lessons, creating quizzes and mastering your studies.",
        "start_learning" to "Start Learning",
        "try_tutor" to "Try AI Tutor",
        "nav_home" to "Home",
        "nav_solve" to "Solve",
        "nav_tutor" to "AI Tutor",
        "nav_summaries" to "Summaries",
        "nav_flashcards" to "Flashcards",
        "nav_quizzes" to "Quizzes",
        "nav_lectures" to "Lectures",
        "nav_library" to "Library",
        "nav_progress" to "Progress",
        "nav_history" to "History",
        "nav_settings" to "Settings",
        "nav_admin" to "Admin",

        // Dashboard
        "greeting_morning" to "Good morning",
        "greeting_afternoon" to "Good afternoon",
        "quick_actions" to "Quick Actions",
        "action_photo_solve" to "Solve from Photo",
        "action_ask_ai" to "Ask AI Tutor",
        "action_analyze_pdf" to "Analyze PDF",
        "action_lecture_rec" to "Lecture Recorder",
        "action_create_cards" to "Create Flashcards",
        "action_generate_quiz" to "Generate Quiz",
        "continue_learning" to "Continue Learning",
        "your_progress" to "Your Progress",
        "questions_solved" to "Problems Solved",
        "quizzes_completed" to "Quizzes Completed",
        "cards_reviewed" to "Cards Reviewed",
        "study_sessions" to "Study Sessions",
        "learning_streak" to "Days Streak",
        "recommended_for_you" to "Recommended for You",
        "usage_label" to "Daily AI Solutions",

        // Solver
        "solver_title" to "Solve a Problem",
        "solver_subtitle" to "Type, paste, or scan academic problems for step-by-step solutions",
        "input_problem_hint" to "Enter your question, mathematical expression, or scientific problem here...",
        "btn_solve" to "Solve with AI",
        "btn_solving" to "Analyzing & Solving...",
        "section_problem" to "Problem",
        "section_subject" to "Subject",
        "section_understanding" to "Understanding",
        "section_given" to "Given Information",
        "section_solution" to "Step-by-Step Solution",
        "section_final_answer" to "Final Answer",
        "section_explanation" to "Explanation",
        "section_check_understanding" to "Check Your Understanding",
        "sample_problems" to "Quick Sample Problems",

        // Tutor
        "tutor_title" to "StudyMate Tutor",
        "tutor_subtitle" to "Personal 24/7 academic tutor tailored to your major",
        "tutor_hint" to "Ask anything about your courses...",
        "quick_explain" to "Explain this concept",
        "quick_example" to "Give me an example",
        "quick_simplify" to "Explain it more simply",
        "quick_quiz" to "Quiz me on this",
        "quick_arabic" to "Explain this in Arabic",

        // Summary
        "summary_title" to "Summarize My Lesson",
        "summary_input_hint" to "Paste lesson text, lecture transcription, or article content...",
        "length_short" to "Short",
        "length_standard" to "Standard",
        "length_detailed" to "Detailed",
        "btn_summarize" to "Generate Smart Summary",
        "overview" to "Overview",
        "key_concepts" to "Key Concepts",
        "definitions" to "Important Definitions",
        "formulas" to "Important Formulas & Rules",
        "examples" to "Concrete Examples",
        "things_to_remember" to "Things to Remember",
        "quick_review" to "Quick Review Checklist",

        // Flashcards
        "flashcards_title" to "Study Flashcards",
        "flashcards_subtitle" to "Master active recall and spaced repetition",
        "btn_flip" to "Tap to Flip",
        "easy" to "Easy",
        "medium" to "Medium",
        "hard" to "Hard",
        "card_mastered" to "Mastered",
        "new_deck" to "Create New Deck",

        // Quiz
        "quiz_title" to "AI Quiz Generator",
        "subject_label" to "Subject",
        "topic_label" to "Topic",
        "num_questions" to "Questions Count",
        "difficulty" to "Difficulty",
        "btn_generate_quiz" to "Generate Quiz",
        "quiz_score" to "Your Score",
        "weak_topics" to "Areas to Strengthen",
        "btn_submit" to "Submit Answers",

        // Lecture
        "lecture_title" to "Lecture Recorder",
        "lecture_subtitle" to "Record oral lectures & automatically synthesize notes",
        "start_recording" to "Start Recording",
        "stop_recording" to "Stop & Analyze",
        "pause_recording" to "Pause",
        "resume_recording" to "Resume",
        "recording_in_progress" to "Recording in progress...",

        // Onboarding
        "onboarding_title" to "Personalize Your Academic Partner",
        "academic_level" to "What is your academic level?",
        "major_question" to "What is your major?",
        "subjects_question" to "What subjects do you study?",
        "learning_pref_question" to "How do you prefer to learn?",
        "main_goal_question" to "What is your main goal?",
        "complete_setup" to "Complete Setup & Enter",

        // Settings & Subscription
        "settings_title" to "Settings & Profile",
        "language_label" to "Language",
        "theme_label" to "Theme",
        "dark_mode" to "Dark Mode",
        "subscription_plan" to "Current Plan",
        "upgrade_pro" to "Upgrade to Pro",
        "free_plan_details" to "15 daily AI solutions, basic summaries & quizzes",
        "pro_plan_details" to "Unlimited AI solutions, advanced vision OCR & export"
    )

    private val ARABIC = mapOf(
        "app_name" to "StudyMate AI",
        "tagline" to "شريكك الدراسي الذكي",
        "hero_title" to "ادرس بذكاء. وافهم أسرع.",
        "hero_subtitle" to "مساعدك الأكاديمي الشخصي المدعوم بالذكاء الاصطناعي لحل المسائل، وفهم الدروس، وإنشاء الاختبارات والتفوق في دراستك.",
        "start_learning" to "ابدأ التعلم",
        "try_tutor" to "جرب المعلم الذكي",
        "nav_home" to "الرئيسية",
        "nav_solve" to "حل المسائل",
        "nav_tutor" to "المعلم الذكي",
        "nav_summaries" to "الملخصات",
        "nav_flashcards" to "البطاقات",
        "nav_quizzes" to "الاختبارات",
        "nav_lectures" to "المحاضرات",
        "nav_library" to "المكتبة",
        "nav_progress" to "التقدم",
        "nav_history" to "السجل",
        "nav_settings" to "الإعدادات",
        "nav_admin" to "لوحة الإدارة",

        // Dashboard
        "greeting_morning" to "صباح الخير",
        "greeting_afternoon" to "مساء الخير",
        "quick_actions" to "إجراءات سريعة",
        "action_photo_solve" to "حل من صورة",
        "action_ask_ai" to "اسأل المعلم الذكي",
        "action_analyze_pdf" to "تحليل ملف PDF",
        "action_lecture_rec" to "تسجيل محاضرة",
        "action_create_cards" to "إنشاء بطاقات تعليمية",
        "action_generate_quiz" to "إنشاء اختبار",
        "continue_learning" to "متابعة التعلم",
        "your_progress" to "تقدمك الأكاديمي",
        "questions_solved" to "المسائل المحلولة",
        "quizzes_completed" to "الاختبارات المنجزة",
        "cards_reviewed" to "البطاقات المراجعة",
        "study_sessions" to "جلسات الدراسة",
        "learning_streak" to "أيام متتالية",
        "recommended_for_you" to "مقترح خصيصاً لك",
        "usage_label" to "حلول AI اليومية",

        // Solver
        "solver_title" to "حل المسائل الأكاديمية",
        "solver_subtitle" to "اكتب المسألة أو التقط صورة للحصول على حل مفصل خطوة بخطوة",
        "input_problem_hint" to "اكتب المسألة أو المعادلة أو السؤال العلمي هنا...",
        "btn_solve" to "حل بالذكاء الاصطناعي",
        "btn_solving" to "جاري التحليل والحل...",
        "section_problem" to "المسألة المكتشفة",
        "section_subject" to "المادة",
        "section_understanding" to "فهم المطلوب",
        "section_given" to "المعطيات",
        "section_solution" to "الحل خطوة بخطوة",
        "section_final_answer" to "الإجابة النهائية",
        "section_explanation" to "الشرح التوضيحي",
        "section_check_understanding" to "اختبر فهمك",
        "sample_problems" to "مسائل نموذجية سريعة",

        // Tutor
        "tutor_title" to "معلم StudyMate الذكي",
        "tutor_subtitle" to "مدرسك الأكاديمي الخاص المتوفر 24/7 والمخصص لتخصصك ومستواك",
        "tutor_hint" to "اسأل عن أي مفهوم، مسألة، أو نظرية...",
        "quick_explain" to "اشرح هذا المفهوم",
        "quick_example" to "أعطني مثالاً عملياً",
        "quick_simplify" to "اشرح بطريقة أبسط",
        "quick_quiz" to "اختبرني في هذا الموضوع",
        "quick_arabic" to "اشرح لي بالعربية",

        // Summary
        "summary_title" to "تلخيص الدروس الذكي",
        "summary_input_hint" to "الصق نص الدرس أو المحاضرة هنا...",
        "length_short" to "قصير",
        "length_standard" to "قياسي",
        "length_detailed" to "مفصل",
        "btn_summarize" to "إنشاء ملخص ذكي",
        "overview" to "نظرة عامة",
        "key_concepts" to "المفاهيم الأساسية",
        "definitions" to "أهم التعريفات",
        "formulas" to "القوانين والمعادلات",
        "examples" to "أمثلة تطبيقية",
        "things_to_remember" to "نقاط يجب تذكرها",
        "quick_review" to "قائمة المراجعة السريعة",

        // Flashcards
        "flashcards_title" to "البطاقات التعليمية",
        "flashcards_subtitle" to "إتقان الحفظ والاسترجاع النشط والتكرار المتباعد",
        "btn_flip" to "انقر للقلب والاطلاع على الإجابة",
        "easy" to "سهل",
        "medium" to "متوسط",
        "hard" to "صعب",
        "card_mastered" to "تم إتقانه",
        "new_deck" to "إنشاء مجموعة جديدة",

        // Quiz
        "quiz_title" to "مولد الاختبارات الذكي",
        "subject_label" to "المادة",
        "topic_label" to "الموضوع",
        "num_questions" to "عدد الأسئلة",
        "difficulty" to "مستوى الصعوبة",
        "btn_generate_quiz" to "توليد الاختبار",
        "quiz_score" to "نتيجتك",
        "weak_topics" to "المواضيع التي تحتاج مراجعة",
        "btn_submit" to "تسليم الإجابات",

        // Lecture
        "lecture_title" to "مسجل المحاضرات الذكي",
        "lecture_subtitle" to "سجل المحاضرات الصوتية وحولها تلقائياً لملخصات وملاحظات",
        "start_recording" to "بدء التسجيل",
        "stop_recording" to "إيقاف واستخراج الملاحظات",
        "pause_recording" to "إيقاف مؤقت",
        "resume_recording" to "استئناف",
        "recording_in_progress" to "جاري تسجيل المحاضرة...",

        // Onboarding
        "onboarding_title" to "تخصيص مساعدك الدراسي",
        "academic_level" to "ما هو مستواك الأكاديمي؟",
        "major_question" to "ما هو تخصصك الدراسي؟",
        "subjects_question" to "ما هي المواد التي تدرسها؟",
        "learning_pref_question" to "كيف تفضل أن تتعلم؟",
        "main_goal_question" to "ما هو هدفك الأساسي؟",
        "complete_setup" to "إتمام الإعداد والبدء",

        // Settings & Subscription
        "settings_title" to "الإعدادات والملف الشخصي",
        "language_label" to "اللغة",
        "theme_label" to "المظهر",
        "dark_mode" to "الوضع الداكن",
        "subscription_plan" to "الخطة الحالية",
        "upgrade_pro" to "الترقية إلى Pro",
        "free_plan_details" to "15 حل مسألة يومياً وملخصات واختبارات أساسية",
        "pro_plan_details" to "حلول واستفسارات غير محدودة وقراءة متقدمة للصور"
    )

    private val FRENCH = mapOf(
        "app_name" to "StudyMate AI",
        "tagline" to "Votre partenaire d'études IA",
        "hero_title" to "Étudiez plus intelligemment. Comprenez plus vite.",
        "hero_subtitle" to "Votre tuteur académique personnel propulsé par l'IA pour résoudre des problèmes, comprendre les cours et réussir vos examens.",
        "start_learning" to "Commencer à apprendre",
        "try_tutor" to "Essayer le Tuteur IA",
        "nav_home" to "Accueil",
        "nav_solve" to "Résoudre",
        "nav_tutor" to "Tuteur IA",
        "nav_summaries" to "Résumés",
        "nav_flashcards" to "Flashcards",
        "nav_quizzes" to "Quiz",
        "nav_lectures" to "Cours audio",
        "nav_library" to "Bibliothèque",
        "nav_progress" to "Progrès",
        "nav_history" to "Historique",
        "nav_settings" to "Paramètres",
        "nav_admin" to "Admin",

        "greeting_morning" to "Bonjour",
        "greeting_afternoon" to "Bon après-midi",
        "quick_actions" to "Actions rapides",
        "action_photo_solve" to "Résoudre par photo",
        "action_ask_ai" to "Demander au Tuteur",
        "action_analyze_pdf" to "Analyser un PDF",
        "action_lecture_rec" to "Enregistrer un cours",
        "action_create_cards" to "Créer des flashcards",
        "action_generate_quiz" to "Générer un quiz",
        "continue_learning" to "Continuer l'apprentissage",
        "your_progress" to "Vos progrès",
        "questions_solved" to "Problèmes résolus",
        "quizzes_completed" to "Quiz terminés",
        "cards_reviewed" to "Cartes révisées",
        "study_sessions" to "Sessions d'étude",
        "learning_streak" to "Jours consécutifs",
        "recommended_for_you" to "Recommandé pour vous",
        "usage_label" to "Solutions IA quotidiennes",

        "solver_title" to "Résoudre un problème",
        "solver_subtitle" to "Saisissez ou scannez vos problèmes académiques pour une solution détaillée",
        "input_problem_hint" to "Écrivez votre problème ou question scientifique ici...",
        "btn_solve" to "Résoudre avec l'IA",
        "btn_solving" to "Analyse et résolution...",
        "section_problem" to "Problème",
        "section_subject" to "Matière",
        "section_understanding" to "Compréhension",
        "section_given" to "Données du problème",
        "section_solution" to "Solution étape par étape",
        "section_final_answer" to "Réponse finale",
        "section_explanation" to "Explication pédagogique",
        "section_check_understanding" to "Vérifiez votre compréhension",
        "sample_problems" to "Exemples rapides",

        "tutor_title" to "Tuteur StudyMate",
        "tutor_subtitle" to "Votre tuteur académique 24/7 adapté à votre filière",
        "tutor_hint" to "Posez n'importe quelle question sur vos cours...",
        "quick_explain" to "Expliquer ce concept",
        "quick_example" to "Donner un exemple",
        "quick_simplify" to "Expliquer plus simplement",
        "quick_quiz" to "Teste-moi là-dessus",
        "quick_arabic" to "Expliquer en arabe",

        "summary_title" to "Résumer mon cours",
        "summary_input_hint" to "Collez le texte du cours ici...",
        "length_short" to "Court",
        "length_standard" to "Standard",
        "length_detailed" to "Détaillé",
        "btn_summarize" to "Générer le résumé",
        "overview" to "Aperçu",
        "key_concepts" to "Concepts clés",
        "definitions" to "Définitions importantes",
        "formulas" to "Formules et règles",
        "examples" to "Exemples concrets",
        "things_to_remember" to "À retenir",
        "quick_review" to "Liste de révision rapide",

        "flashcards_title" to "Flashcards d'étude",
        "flashcards_subtitle" to "Répétition espacée et mémorisation active",
        "btn_flip" to "Toucher pour retourner",
        "easy" to "Facile",
        "medium" to "Moyen",
        "hard" to "Difficile",
        "card_mastered" to "Maîtrisé",
        "new_deck" to "Nouveau paquet",

        "quiz_title" to "Générateur de Quiz IA",
        "subject_label" to "Matière",
        "topic_label" to "Sujet",
        "num_questions" to "Nombre de questions",
        "difficulty" to "Difficulté",
        "btn_generate_quiz" to "Générer le quiz",
        "quiz_score" to "Votre score",
        "weak_topics" to "Points à renforcer",
        "btn_submit" to "Soumettre",

        "lecture_title" to "Enregistreur de cours",
        "lecture_subtitle" to "Enregistrez et extrayez des notes structurées",
        "start_recording" to "Commencer l'enregistrement",
        "stop_recording" to "Arrêter et analyser",
        "pause_recording" to "Pause",
        "resume_recording" to "Reprendre",
        "recording_in_progress" to "Enregistrement en cours...",

        "onboarding_title" to "Personnalisez votre tuteur",
        "academic_level" to "Quel est votre niveau d'études ?",
        "major_question" to "Quelle est votre filière / spécialité ?",
        "subjects_question" to "Quelles matières étudiez-vous ?",
        "learning_pref_question" to "Comment préférez-vous apprendre ?",
        "main_goal_question" to "Quel est votre objectif principal ?",
        "complete_setup" to "Terminer et commencer",

        "settings_title" to "Paramètres et profil",
        "language_label" to "Langue",
        "theme_label" to "Thème",
        "dark_mode" to "Mode sombre",
        "subscription_plan" to "Abonnement actuel",
        "upgrade_pro" to "Passer à Pro",
        "free_plan_details" to "15 solutions IA par jour et résumés de base",
        "pro_plan_details" to "Solutions et analyses illimitées avec OCR haute précision"
    )
}
